#Name: Davids Jalisevs
#License: GNU General Public License 3.0

OBJS = Semaphore.o signal.o
SOURCE = Semaphore.cpp signal.cpp
HEADER = Semaphore.h
OUT = signal.out
CC = g++
LFLAGS =

all: $(OBJS)
	$(CC) $(OBJS) -o $(OUT) $(LFLAGS)
